#!/bin/bash

BASE=${1:-"alpine"}
IMAGE="pmyadlowsky/gusher:alpine"

echo "make sure commits are current and pushed up"
sleep 3

docker build --rm=true -f Dockerfile.$BASE -t $IMAGE .
docker push $IMAGE
