#! /bin/bash

LOGDIR="/var/log/nowcall"
STORE="/vol/store"
APP="$1"
THREADS="$2"

mkdir -p $LOGDIR
chown gusher $LOGDIR
mkdir -p $STORE
chown -R gusher $STORE

su -c "(cd ~/nowcall; /usr/local/bin/gusher -t $THREADS ./$APP)" - gusher
