#! /bin/bash

LOGDIR="/var/log/nowcall"
STORE="/vol/store"
PROFILE="/vol/profile"
APP="$1"
THREADS="$2"
PULSE="$STORE/$APP.pulse"

mkdir -p $LOGDIR
chown gusher $LOGDIR
mkdir -p $STORE
chown -R gusher $STORE

su -c "(cd ~/nowcall; /usr/local/bin/gusher -h $PULSE -t $THREADS ./$APP)" - gusher
